import {
    StorybookIcon,
    BoardIcon,
    BoardColorIcon,
    ToolsIcon,
    WindowMaximizeIcon,
    WindowRestoreIcon,
    WindowMinimizeIcon,
    TabsIcon,
    HistoryIcon,
    GitIcon,
    CloseIcon,
    ProgressIcon,
    PersephoneIcon,
    PlusIcon,
    CircleIcon,
    FilterArrowUpIcon,
    FilterArrowDownIcon,
    ArrowUpIcon,
    FolderUpIcon,
    ArrowDownIcon,
    ArrowRightIcon,
    ArrowLeftIcon,
    ConfirmIcon,
    ErrorIcon,
    InfoIcon,
    SuccessIcon,
    WarningIcon,
    DragHandleIcon,
    ResizeHandleIcon,
    CopyIcon,
    CursorIcon,
    EmptyIcon,
    CheckIcon,
    OpenFileIcon,
    NewWindowIcon,
    GroupIcon,
    GraphGroupIcon,
    RunIcon,
    RunAllIcon,
    SettingsIcon,
    CheckedIcon,
    UncheckedIcon,
    IndeterminateIcon,
    RadioCheckedIcon,
    RadioUncheckedIcon,
    FilterTableIcon,
    QuestionIcon,
    DeleteIcon,
    PasteIcon,
    CutIcon,
    ChevronUpIcon,
    ChevronDownIcon,
    ChevronRightIcon,
    ChevronLeftIcon,
    RefreshIcon,
    ColumnsIcon,
    SunIcon,
    MoonIcon,
    CompareIcon,
    SaveIcon,
    DuplicateIcon,
    RenameIcon,
    FolderOpenIcon,
    LockIcon,
    UnlockIcon,
    KeyOffIcon,
    NewFileIcon,
    NewFolderIcon,
    FolderPlusIcon,
    RemoveIcon,
    ClearListIcon,
    CollapseAllIcon,
    ExpandAllIcon,
    CompactViewIcon,
    NormalViewIcon,
    NavPanelIcon,
    SearchIcon,
    GlobeIcon,
    OpenLinkIcon,
    ViewListIcon,
    WrapTextIcon,
    LogIcon,
    TerminalIcon,
    ViewLandscapeIcon,
    ViewLandscapeBigIcon,
    ViewPortraitIcon,
    ViewPortraitBigIcon,
    StopIcon,
    PlayIcon,
    PauseIcon,
    NextTrackIcon,
    ShuffleIcon,
    CaseSensitiveIcon,
    HomeIcon,
    VolumeIcon,
    VolumeMutedIcon,
    BookmarkIcon,
    BookmarkFilledIcon,
    StarIcon,
    StarFilledIcon,
    PinIcon,
    PinFilledIcon,
    ScriptLibraryIcon,
    SnipIcon,
    DownloadIcon,
    UploadIcon,
    McpIcon,
    MemoryIcon,
    ArchiveIcon,
    TagIcon,
    SortAlphaIcon,
    WebScraperIcon,
    SwapIcon,
    MoreVertIcon,
    MoreHorizIcon,
    VlcIcon,
    PlayerIcon,
} from "./icons";
import type { SvgIconComponent } from "./icons";

// Keep this list in sync with the explicit exports in icons.ts. The registry is the
// single source of truth for IconName; adding an icon still requires a manual entry here.
// Excluded by design: language-icons.ts, components/icons/* resolver components,
// SvgIcon/SvgIconProps/SvgIconComponent, createIcon, and createIconWithViewBox.
const ICONS = {
    "storybook": StorybookIcon,
    "board": BoardIcon,
    "board-color": BoardColorIcon,
    "tools": ToolsIcon,
    "window-maximize": WindowMaximizeIcon,
    "window-restore": WindowRestoreIcon,
    "window-minimize": WindowMinimizeIcon,
    "tabs": TabsIcon,
    "history": HistoryIcon,
    "git": GitIcon,
    "close": CloseIcon,
    "progress": ProgressIcon,
    "persephone": PersephoneIcon,
    "plus": PlusIcon,
    "circle": CircleIcon,
    "filter-arrow-up": FilterArrowUpIcon,
    "filter-arrow-down": FilterArrowDownIcon,
    "arrow-up": ArrowUpIcon,
    "folder-up": FolderUpIcon,
    "arrow-down": ArrowDownIcon,
    "arrow-right": ArrowRightIcon,
    "arrow-left": ArrowLeftIcon,
    "confirm": ConfirmIcon,
    "error": ErrorIcon,
    "info": InfoIcon,
    "success": SuccessIcon,
    "warning": WarningIcon,
    "drag-handle": DragHandleIcon,
    "resize-handle": ResizeHandleIcon,
    "copy": CopyIcon,
    "cursor": CursorIcon,
    "empty": EmptyIcon,
    "check": CheckIcon,
    "open-file": OpenFileIcon,
    "new-window": NewWindowIcon,
    "group": GroupIcon,
    "graph-group": GraphGroupIcon,
    "run": RunIcon,
    "run-all": RunAllIcon,
    "settings": SettingsIcon,
    "checked": CheckedIcon,
    "unchecked": UncheckedIcon,
    "indeterminate": IndeterminateIcon,
    "radio-checked": RadioCheckedIcon,
    "radio-unchecked": RadioUncheckedIcon,
    "filter-table": FilterTableIcon,
    "question": QuestionIcon,
    "delete": DeleteIcon,
    "paste": PasteIcon,
    "cut": CutIcon,
    "chevron-up": ChevronUpIcon,
    "chevron-down": ChevronDownIcon,
    "chevron-right": ChevronRightIcon,
    "chevron-left": ChevronLeftIcon,
    "refresh": RefreshIcon,
    "columns": ColumnsIcon,
    "sun": SunIcon,
    "moon": MoonIcon,
    "compare": CompareIcon,
    "save": SaveIcon,
    "duplicate": DuplicateIcon,
    "rename": RenameIcon,
    "folder-open": FolderOpenIcon,
    "lock": LockIcon,
    "unlock": UnlockIcon,
    "key-off": KeyOffIcon,
    "new-file": NewFileIcon,
    "new-folder": NewFolderIcon,
    "folder-plus": FolderPlusIcon,
    "remove": RemoveIcon,
    "clear-list": ClearListIcon,
    "collapse-all": CollapseAllIcon,
    "expand-all": ExpandAllIcon,
    "compact-view": CompactViewIcon,
    "normal-view": NormalViewIcon,
    "nav-panel": NavPanelIcon,
    "search": SearchIcon,
    "globe": GlobeIcon,
    "open-link": OpenLinkIcon,
    "view-list": ViewListIcon,
    "wrap-text": WrapTextIcon,
    "log": LogIcon,
    "terminal": TerminalIcon,
    "view-landscape": ViewLandscapeIcon,
    "view-landscape-big": ViewLandscapeBigIcon,
    "view-portrait": ViewPortraitIcon,
    "view-portrait-big": ViewPortraitBigIcon,
    "stop": StopIcon,
    "play": PlayIcon,
    "pause": PauseIcon,
    "next-track": NextTrackIcon,
    "shuffle": ShuffleIcon,
    "case-sensitive": CaseSensitiveIcon,
    "home": HomeIcon,
    "volume": VolumeIcon,
    "volume-muted": VolumeMutedIcon,
    "bookmark": BookmarkIcon,
    "bookmark-filled": BookmarkFilledIcon,
    "star": StarIcon,
    "star-filled": StarFilledIcon,
    "pin": PinIcon,
    "pin-filled": PinFilledIcon,
    "script-library": ScriptLibraryIcon,
    "snip": SnipIcon,
    "download": DownloadIcon,
    "upload": UploadIcon,
    "mcp": McpIcon,
    "memory": MemoryIcon,
    "archive": ArchiveIcon,
    "tag": TagIcon,
    "sort-alpha": SortAlphaIcon,
    "web-scraper": WebScraperIcon,
    "swap": SwapIcon,
    "more-vert": MoreVertIcon,
    "more-horiz": MoreHorizIcon,
    "vlc": VlcIcon,
    "player": PlayerIcon,
} as const satisfies Record<string, SvgIconComponent>;

export type IconName = keyof typeof ICONS;

export function getIcon(name: string): SvgIconComponent | undefined {
    return ICONS[name as IconName];
}
