/** The complete, ordered set of CSS color variables every theme must provide. */
export const THEME_COLOR_VARS = [
    "--color-bg-default",
    "--color-bg-dark",
    "--color-bg-light",
    "--color-bg-selection",
    "--color-bg-tree-selection",
    "--color-bg-scrollbar",
    "--color-bg-scrollbar-thumb",
    "--color-bg-message",
    "--color-bg-overlay",
    "--color-bg-overlay-hover",
    "--color-bg-webview",
    "--color-bg-backdrop",
    "--color-text-default",
    "--color-text-dark",
    "--color-text-light",
    "--color-text-selection",
    "--color-text-strong",
    "--color-icon-default",
    "--color-icon-dark",
    "--color-icon-light",
    "--color-icon-disabled",
    "--color-icon-selection",
    "--color-icon-active",
    "--color-border-active",
    "--color-border-default",
    "--color-border-light",
    "--color-shadow-default",
    "--color-grid-header-bg",
    "--color-grid-header-color",
    "--color-grid-data-bg",
    "--color-grid-border",
    "--color-grid-data-color",
    "--color-grid-sel-selected",
    "--color-grid-sel-hovered",
    "--color-grid-sel-border",
    "--color-grid-sel-border-light",
    "--color-misc-blue",
    "--color-misc-link",
    "--color-misc-green",
    "--color-misc-red",
    "--color-misc-yellow",
    "--color-misc-orange",
    "--color-misc-vlc",
    "--color-error-bg",
    "--color-error-text",
    "--color-error-border",
    "--color-error-text-hover",
    "--color-success-bg",
    "--color-success-text",
    "--color-success-border",
    "--color-success-text-hover",
    "--color-primary-bg",
    "--color-primary-text",
    "--color-primary-border",
    "--color-primary-text-hover",
    "--color-warning-bg",
    "--color-warning-text",
    "--color-warning-border",
    "--color-warning-text-hover",
    "--color-highlight-active-match",
    "--color-minimap-bg",
    "--color-minimap-hover-bg",
    "--color-minimap-active-bg",
    "--color-graph-bg",
    "--color-graph-node-default",
    "--color-graph-node-highlight",
    "--color-graph-node-selected",
    "--color-graph-border-default",
    "--color-graph-border-highlight",
    "--color-graph-border-selected",
    "--color-graph-link-default",
    "--color-graph-link-selected",
    "--color-graph-label-bg",
    "--color-graph-label-text",
    "--color-graph-group-border",
    "--color-graph-node-special",
    "--color-graph-border-special",
] as const;

export type ThemeColorVar = typeof THEME_COLOR_VARS[number];

const themeColorVarSet: ReadonlySet<string> = new Set(THEME_COLOR_VARS);

/** Narrows an arbitrary string to one of the theme's declared CSS color variables. */
export function isThemeColorVar(value: string): value is ThemeColorVar {
    return themeColorVarSet.has(value);
}
