import { boardVarsAdmin } from "../../../api/board-vars/admin-api";
import { boards } from "../../../api/boards";
import { downloads } from "../../../api/downloads";
import { editors } from "../../../api/editors";
import { fs } from "../../../api/fs";
import { menuFolders } from "../../../api/menu-folders";
import { recent } from "../../../api/recent";
import { encryption } from "../../../api/shell/encryption";
import { shell } from "../../../api/shell";
import { version } from "../../../api/shell/version";
import { settings } from "../../../api/settings";
import { ui } from "../../../api/ui";
import { appWindow } from "../../../api/window";
import { registerAiVision, registerAiVisionFor } from "ai-vision";
import { describeBoardVars } from "./board-vars";
import { describeBoards } from "./boards";
import { describeDownloads } from "./downloads";
import { describeEditorRegistry } from "./editors";
import { describeFileSystem } from "./fs";
import { describeMenuFolders } from "./menu-folders";
import { describeMenuBar } from "./menu-bar";
import { describeRecentFiles } from "./recent";
import { describeEncryptionService, describeShell, describeVersionService } from "./shell";
import { describeSettings } from "./settings";
import { describeUserInterface } from "./ui";
import { describeWindow } from "./window";
import { describeWindowScreen } from "./window-screen";
import { describeProcess } from "./proc";
import { proc } from "../../../api/proc";
import { describeTools, toolsNode } from "./tools";
import { EventsNode, describeEvents } from "./events";

registerAiVision(EventsNode, describeEvents);

registerAiVisionFor(fs, describeFileSystem);
registerAiVisionFor(settings, describeSettings);
registerAiVisionFor(ui, describeUserInterface);
registerAiVisionFor(shell, describeShell);
registerAiVisionFor(version, describeVersionService);
registerAiVisionFor(encryption, describeEncryptionService);
registerAiVisionFor(appWindow, describeWindow);
registerAiVisionFor(appWindow.menuBar, describeMenuBar);
registerAiVisionFor(appWindow.screen, describeWindowScreen);
registerAiVisionFor(proc, describeProcess);
registerAiVisionFor(boards, describeBoards);
registerAiVisionFor(boardVarsAdmin, describeBoardVars);
registerAiVisionFor(toolsNode, describeTools);
registerAiVisionFor(editors, describeEditorRegistry);
registerAiVisionFor(recent, describeRecentFiles);
registerAiVisionFor(downloads, describeDownloads);
registerAiVisionFor(menuFolders, describeMenuFolders);
