import type { IAiMember } from "ai-vision";

/** Shared automation members for browser-like editor hosts. */
export const BROWSER_AUTOMATION_MEMBERS: readonly IAiMember[] = [
    { name: "snapshot", kind: "method", signature: "snapshot(options?: { tabId?: string; root?: string | { ref: string }; interactive?: boolean; maxNodes?: number; maxChars?: number }): Promise<string>", summary: "Get the accessibility snapshot. Start with interactive: true or root: a CSS selector/ref to narrow large pages. maxNodes and maxChars bound the output; a shortened result ends with omitted dialogs/landmarks and a recovery hint. The default snapshot budget is 18,000 characters, below the outer MCP call result cap of 20,000. Every line carries a ref usable by click/hover/type/select. Plain strings in root are CSS selectors; refs must be passed as { ref: \"e12\" }. The result may begin with # <overlay> when a modal covers the page." },
    { name: "click", kind: "method", signature: "click(locator: string | { ref: string }, options?: { tabId?: string; button?: 'left' | 'right' | 'middle'; clickCount?: number; modifiers?: ('Alt' | 'Control' | 'Meta' | 'Shift')[]; position?: { x: number; y: number }; force?: boolean; synthetic?: boolean; nth?: number; timeout?: number }): Promise<void>", summary: "Click with trusted mouse input by default. Ambiguous visible selectors fail immediately; use a ref, narrow the selector, or choose a zero-based visible match with nth. position is relative to the element's border-box top-left. force skips actionability checks; synthetic opts into the legacy DOM path." },
    { name: "hover", kind: "method", signature: "hover(locator: string | { ref: string }, options?: { tabId?: string; position?: { x: number; y: number }; modifiers?: ('Alt' | 'Control' | 'Meta' | 'Shift')[]; force?: boolean; synthetic?: boolean; nth?: number; timeout?: number }): Promise<void>", summary: "Move the real pointer once over a selector or ref. Browser webviews receive trusted pointer events but do not apply CSS :hover. Ambiguous visible selectors fail immediately; use a ref, narrow the selector, or choose a zero-based visible match with nth. position is relative to the element's border-box top-left. force skips actionability checks; synthetic opts into legacy DOM events." },
    { name: "type", kind: "method", signature: "type(locator: string | { ref: string }, text: string, options?: { tabId?: string; slowly?: boolean; submit?: boolean; synthetic?: boolean; nth?: number; timeout?: number; force?: boolean }): Promise<void>", summary: "Replace an editable input or contenteditable value using trusted CDP input. slowly sends real key events; submit presses trusted Enter. Native date/time/color/range controls use validated value assignment and untrusted input/change events. synthetic opts into the legacy path.", caution: "clears/replaces the target value" },
    { name: "select", kind: "method", signature: "select(locator: string | { ref: string }, values: string | string[], options?: { tabId?: string; nth?: number; timeout?: number; force?: boolean }): Promise<void>", summary: "Select validated values on a native <select>. Dispatches programmatic, untrusted bubbling input then change events; multiple values require a multiple select. It currently also runs pointer actionability and hit-testing. Custom dropdowns use trusted click() + pressKey()." },
    { name: "check", kind: "method", signature: "check(locator: string | { ref: string }, options?: { tabId?: string; nth?: number; timeout?: number; force?: boolean }): Promise<void>", summary: "Trusted-click a checkbox or radio only when its state differs, then verify the new state." },
    { name: "uncheck", kind: "method", signature: "uncheck(locator: string | { ref: string }, options?: { tabId?: string; nth?: number; timeout?: number; force?: boolean }): Promise<void>", summary: "Trusted-click a checked checkbox and verify the result. Radio buttons cannot be unchecked." },
    { name: "clear", kind: "method", signature: "clear(locator: string | { ref: string }, options?: { tabId?: string; nth?: number; timeout?: number; force?: boolean }): Promise<void>", summary: "Clear editable text with trusted focus and Delete input." },
    { name: "pressKey", kind: "method", signature: "pressKey(key: string, options?: { tabId?: string; target?: string | { ref: string }; nth?: number; timeout?: number; synthetic?: boolean }): Promise<void>", summary: "Press a trusted key or compound combination on the focused element. A target locator is focused by trusted click first. Ctrl+C/V use the real OS clipboard; Persephone does not save or restore clipboard contents." },
    { name: "keyDown", kind: "method", signature: "keyDown(key: string, options?: { tabId?: string; target?: string | { ref: string }; nth?: number; timeout?: number; synthetic?: boolean }): Promise<void>", summary: "Send trusted keyDown and retain the key state until keyUp; use this for held-modifier sequences." },
    { name: "keyUp", kind: "method", signature: "keyUp(key: string, options?: { tabId?: string; target?: string | { ref: string }; nth?: number; timeout?: number; synthetic?: boolean }): Promise<void>", summary: "Release a key previously held with keyDown." },
    { name: "drag", kind: "method", signature: "drag(source: string | { ref: string }, destination: string | { ref: string }, options?: { tabId?: string; position?: { x: number; y: number }; targetPosition?: { x: number; y: number }; modifiers?: ('Alt' | 'Control' | 'Meta' | 'Shift')[]; force?: boolean; nth?: number; timeout?: number }): Promise<void>", summary: "Drag actionable elements in the same frame. HTML5 drag data is intercepted and replayed; cross-frame drags fail." },
    { name: "fillForm", kind: "method", signature: "fillForm(fields: IBrowserFormField[]): Promise<void>", summary: "Apply named type/select/check/uncheck fields sequentially. Stops at the first error and names that field; prior changes remain." },
    { name: "setInputFiles", kind: "method", signature: "setInputFiles(locator: string | { ref: string }, paths: string[], options?: { tabId?: string }): Promise<void>", summary: "Set existing local files directly on a hidden or visible input[type=file]. Does not open or intercept the native file chooser." },
    { name: "evaluate", kind: "method", signature: "evaluate(code: string | Function, options?: { tabId?: string; args?: JsonValue[] }): Promise<unknown>", summary: "Run a string expression or invoke a Function/function-expression with JSON-safe args. String arrow functions are invoked, not returned.", caution: "arbitrary page JavaScript can mutate the page" },
    { name: "waitFor", kind: "method", signature: "waitFor(options: { selector?: string; state?: 'attached' | 'detached' | 'visible' | 'hidden'; text?: string; textGone?: string; time?: number; timeout?: number; tabId?: string }): Promise<void>", summary: "Wait for one selector, text, textGone, or time condition. Selector defaults to attached; visible checks positive size, visibility, and display. Uses 100 ms timers and defaults to 10000 ms." },
    { name: "screenshot", kind: "method", signature: "screenshot(options?: { tabId?: string; target?: string | { ref: string }; fullPage?: boolean; format?: 'png' | 'jpeg'; quality?: number; nth?: number }): Promise<IBrowserScreenshot | undefined>", summary: "Capture a page, element, or browser full page as PNG/JPEG. target and fullPage cannot be combined; board/app fullPage is unsupported; cross-origin frame refs cannot be element targets." },
    { name: "networkRequests", kind: "method", signature: "networkRequests(options?: { tabId?: string }): Promise<IBrowserNetworkRequest[]>", summary: "Get recorded request history; only browser pages have network history." },
    { name: "waitForResponse", kind: "method", signature: "waitForResponse(urlOrRegex: string | RegExp, options?: { timeout?: number; tabId?: string; includeBody?: boolean; maxBodyBytes?: number }): Promise<IBrowserResponse>", summary: "Wait for a matching final response (headers; with includeBody, until its body finishes). Arm before triggering the request; strings match exactly and RegExp supports query matching." },
    { name: "consoleMessages", kind: "method", signature: "consoleMessages(options?: { tabId?: string; since?: number; level?: 'debug' | 'info' | 'log' | 'warning' | 'error' }): Promise<object[]>", summary: "Read recent copied console records. since is a Unix-epoch timestamp in milliseconds; level filters normalized console levels. Capture starts on the first automation command and retains at most 500 records." },
    { name: "pageErrors", kind: "method", signature: "pageErrors(options?: { tabId?: string }): Promise<object[]>", summary: "Read recent uncaught page exceptions. Capture starts on the first automation command and retains at most 500 records." },
];
