classDiagram
    class EditorModel~TState~ {
        <<abstract>>
        +id: string
        +editorId: string
        +state: TOneState~TState~
        +traits: TraitSet
        +page: IPageHost?
        +applyRestoreData(data)
        +switchFrom(oldEditor)*
        +restore()*
        +setPage(page)
        +beforeNavigateAway(newEditor)
        +onMainEditorChanged(newMainEditor)
        +survivesNavigation(sourceLink) bool
        +keepAliveOnNavigation() bool
        +getDescriptor(): HostDescriptor
        +dispose()
    }

    class IContentHost {
        <<interface>>
        +id: string
        +type: "textFile"
        +state: TOneState~IContentHostState~
        +stateStorage: EditorStateStorage
        +pipe: IContentPipe?
        +changeContent(content, byUser?)
        +changeLanguage(language)
        +getDescriptor(): HostDescriptor
        +dispose()
    }

    class IContentHostTrait {
        <<interface>>
        +extractContentHost(): IContentHost
        +inheritContentHost(host)
    }

    class TextFileModel {
        implements IContentHost
        +pipe: IContentPipe
        +io: TextFileIOModel
        +encryption: TextFileEncryptionModel
    }

    class NoteItemEditModel {
        implements IContentHost
        -notebookModel: NotebookSource
        -noteId: string
    }

    IContentHost <|.. TextFileModel
    IContentHost <|.. NoteItemEditModel

    EditorModel <|-- MonacoEditor
    EditorModel <|-- GridEditor
    EditorModel <|-- MarkdownEditor
    EditorModel <|-- SvgEditor
    EditorModel <|-- HtmlEditor
    EditorModel <|-- MermaidEditor
    EditorModel <|-- NotebookEditor
    EditorModel <|-- LinkEditor
    EditorModel <|-- LogViewEditor
    EditorModel <|-- DrawEditor
    EditorModel <|-- RestClientEditor
    EditorModel <|-- BrowserEditorModel
    EditorModel <|-- ImageEditor
    EditorModel <|-- ArchiveEditor
    EditorModel <|-- VideoEditor
    EditorModel <|-- McpInspectorEditorModel
    EditorModel <|-- CategoryEditorModel
    EditorModel <|-- AboutEditor
    EditorModel <|-- SettingsEditor
    EditorModel <|-- StorybookEditorModel

    MonacoEditor ..|> IContentHostTrait
    GridEditor ..|> IContentHostTrait
    MarkdownEditor ..|> IContentHostTrait
    SvgEditor ..|> IContentHostTrait
    HtmlEditor ..|> IContentHostTrait
    MermaidEditor ..|> IContentHostTrait
    NotebookEditor ..|> IContentHostTrait
    LinkEditor ..|> IContentHostTrait
    LogViewEditor ..|> IContentHostTrait
    DrawEditor ..|> IContentHostTrait
    RestClientEditor ..|> IContentHostTrait

    MonacoEditor o-- IContentHost : composes
    GridEditor o-- IContentHost : composes
    MarkdownEditor o-- IContentHost : composes
    NotebookEditor o-- IContentHost : composes
